### ISSUE TITLE
Types not found on fresh install and import

### ISSUE THREAD

**Issue by AldieryGonzalez** [sjwall/mdx-mermaid#111]
**Describe the bug**
Types are not found for the package, although it does find the 

**To Reproduce**
Steps to reproduce the behaviour including how the markdown file is processed:
1. Import Package as seen below

**Expected behavior**
This is not breaking but just to have some stronger types so this error doesnt break my linters

**Screenshots**
![image](https://github.com/user-attachments/assets/5b836120-7f3c-42d8-acde-2de9e4c091f2)
![image](https://github.com/user-attachments/assets/2027790c-6574-48d2-84a0-8c3e9092b087)

**Stack trace**
Could not find a declaration file for module 'mdx-mermaid'. '/home/aldiery/repos/paradigm-study-web/node_modules/mdx-mermaid/lib/mdxast-mermaid.mjs' implicitly has an 'any' type.
  There are types at '/home/aldiery/repos/paradigm-study-web/node_modules/mdx-mermaid/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'mdx-mermaid' library may need to update its package.json or typings.

**Tool chain used:**
- NextJs MDX
- Typescript 
- EcmaScript Modules

**Comment by Thijmen** [comment]
Same here, it seems.
```
"mdx-mermaid": "^2.0.1",
```

**Comment by sjwall** [comment]
Thank you for raising this, issue is fixed in `v2.0.2`
