### ISSUE TITLE
Pass in mermaid options

### ISSUE THREAD

**Issue by audunsol** [sjwall/mdx-mermaid#2]
**Describe the solution you'd like**
Would it be possible to have the opportunity to pass in mermaid options via this plugin? E.g.

```typescript
mermaid.initialize({
  startOnLoad: true,
  securityLevel: 'loose' // <-- Example of additional stuff I think would be nice...
})
```

**Describe alternatives you've considered**
Considered to try using the solution from [here](https://github.com/facebook/docusaurus/issues/1258#issuecomment-594393744) directly instead (but the plugin looks cleaner).

**Additional context**
Thanks for the plugin!

**Comment by sjwall** [comment]
I have added this in v1.1.0

Let me know how it goes

**Comment by audunsol** [comment]
Sorry for the long delay here!

But just wanted to let you know it works perfectly for me now. Thanks!

**Comment by markuman** [comment]
How do I set `securityLevel: 'loose' ` in a docusaurus 2 setup?

```js
docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          remarkPlugins: [require('mdx-mermaid')],
          ...
}
```
