### ISSUE TITLE
Theme Variables not working?

### ISSUE THREAD

**Issue by mbalex99** [sjwall/mdx-mermaid#3]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour including how the markdown file is processed:
1. Setup themes variables '...'

This is my docusaurus.config.js. Notice that I 

```js
  presets: [
    [
      "@docusaurus/preset-classic",
      {
        docs: {
          remarkPlugins: [
            [require("mdx-mermaid"), { mermaid: { theme: "dark", themeVariables: { fontFamily: '"Arial"' } } }],
          ],
```

2. Create diagram like '....'

I have a diagram like so:

~~~
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```
~~~

3. Build with '....'

Everything is fine. 

Notice that the fontFamily is still the default:

<img width="1389" alt="Screen Shot 2021-08-25 at 10 08 59 AM" src="https://user-images.githubusercontent.com/2183729/130834884-f50a24d5-8852-422c-8f10-cae2a3cf6526.png">

**Expected behavior**

The font family should be `"Arial"` as defined the the docusaurus.config.js

**Screenshots**

See above

**Stack trace**
If applicable, add the stack trace for the exception thrown to help trace your problem.

There is no exception

**Tool chain used:**
What tool chain is used.

1. Yarn
2. Docusaurus v2 Beta 5

**Comment by sjwall** [comment]
Thank you for raising the issue, looks like from your second comment that this is a Mermaid bug so closing this here
