### ISSUE TITLE
Theme variables only applied to first diagram

### ISSUE THREAD

**Issue by dprothero** [sjwall/mdx-mermaid#33]
**Describe the bug**
If you defined `themeVariables` to customize colors, fonts, etc., the customizations are only applied to the first diagram in the Markdown document. The second diagram is rendered with the default theme.

**To Reproduce**
1. Setup themes variables:
   ```
    remarkPlugins: [
      [
        require("mdx-mermaid"),
        {
          mermaid: {
            theme: "base",
            themeVariables: {
              primaryColor: "lime",
            },
          },
        },
      ],
    ],
   ```
2. Add two diagrams to a Markdown file:
   ````
   ```mermaid
   graph TD;
        A-->B;
        A-->C;
        B-->D;
        C-->D;
    ```
  
    ```mermaid
    graph TD;
        A-->B;
        A-->C;
        B-->D;
        C-->D;
    ```
   ````
3. Build with `yarn start`
4. See two diagrams with different colors. (see screenshot)

**Expected behavior**
All diagrams should share the same theme configuration.

**Screenshots**
![image](https://user-images.githubusercontent.com/1897006/155383907-e2100e09-233d-4e22-beab-0cd3732e1fe7.png)

**Stack trace**
N/A

**Tool chain used:**
Docusaurus 2.0.0-beta.9, mdx-mermaid 1.2.1

**Additional context**
When experimenting with different colors, you have to CTRL-C to break `yarn start` and then run it again to see the changes.

**Comment by ivorc** [comment]
Great to see this has been fixed. It would be lovely to see a tagged release with this fix if possible? Thanks!
