### ISSUE TITLE
Does not follow theme when toggled

### ISSUE THREAD

**Issue by lukejgaskell** [sjwall/mdx-mermaid#4]
**Describe the bug**
The diagrams do not match the theme when it's toggles with docusaurus

**To Reproduce**
Steps to reproduce the behavior including how the markdown file is processed:
1. Start on light mode with mermaid in light mode.
2. Toggle to dark mode.
3. Diagrams will not change to dark mode.

**Expected behavior**
I would expect the diagrams theme to match the toggled theme.

**Comment by sjwall** [comment]
I haven't had time to investigate this
The diagram style is controlled by Mermaid and Docusaurus uses `data-theme="dark"` attribute on the HTML element
My guess would be to have a custom Mermaid theme that uses this attribute to switch between Mermaid themes
