### ISSUE TITLE
Upgrade mermaid to 8.12 or even 9?

### ISSUE THREAD

**Issue by rethab** [sjwall/mdx-mermaid#54]
Hi, in package.json, you're saying mermaid needs to be lower than 8.12. Is there a reason for that?

The reason I'd like to avoid mermaid 8.11.X is that it brings `@percy/migrate` as a regular dependency, which in turn depends on [`colors` at version 1.4.2](https://github.com/Marak/colors.js/issues/289).

With 8.12 that dependency was moved to `devDependencies`: https://github.com/mermaid-js/mermaid/pull/2260

If you need help with this, I'd be happy to assist.

**Comment by BenjaminEHowe** [comment]
This issue seems to be related to https://github.com/sjwall/mdx-mermaid/issues/51.

**Comment by rethab** [comment]
Until this gets upgraded, or even [integrated into docusaurus officially](https://github.com/facebook/docusaurus/pull/7490), this is how you can force a new version of mermaid in your package.json:

```json
  "overrides": {
    "mermaid": "^8.12.0"
  },
```

**Comment by sjwall** [comment]
This will be fixed by #18 and I am looking into getting this out in the next couple of weeks

The reason for the mermaid version selection is documented here https://sjwall.github.io/mdx-mermaid/docs/mermaid-versions/

**Comment by sjwall** [comment]
This is resolved with release `v2.0.0-rc1`. I'll promote to `v2.0.0` in a week or so if there are no bugs reported

**Comment by sjwall** [comment]
For use with Docusaurus this is resolved in `v1.3.0`
