### ISSUE TITLE
Docusaurus 2.1.0 has another config.

### ISSUE THREAD

**Issue by DraTeots** [sjwall/mdx-mermaid#68]
**Describe the bug**

Running 

```bash
npx create-docusaurus@latest test-code classic --typescript
# or
npx create-docusaurus@latest test-code classic
```

Creates a website, that has another config strcture, [than in examples](https://github.com/sjwall/mdx-mermaid/blob/main/doc/docusaurus.config.js). While look similar, seems there is no "remarkPlugins" in JS definition. As there is no createConfig() and other changes. 

Experiments with importing mdxMermaid and adding to remarkPlugins got errors like: 

config 

```javascript
  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          remarkPlugins: [mdxMermaid.default],
```

errors:

```
> docusaurus start

[INFO] Starting the development server...
[ERROR] ValidationError: "beforeDefaultRemarkPlugins[0]" must not be a sparse array item
[INFO] Docusaurus version: 2.1.0
Node version: v16.17.1
```

I also tried to npm instlal mdx-markdown@^2.0.0. but it was not found in npm. 

related to https://github.com/sjwall/mdx-mermaid/issues/64

**Comment by chungkwonryu** [comment]
@DraTeots 
Hi. I was also tried it, and succeed to adapt sjwall's mdx-mermaid plugin to docusaurus 2.1 (the newest version)

At first, you should write this to the top of the config file.
`const mdxMermaid = require('mdx-mermaid');`

And then, just add below presets to docs,
```
docs: {
   ... some codes...
   remarkPlugins: [mdxMermaid],
},
```

I hope it works for you, too!

**Comment by PackElend** [comment]
I would have faced the same issue thx a lot for sharing!

by the way how is ensured that the right Mermaid version is used?

**Comment by PackElend** [comment]
I'm on v2.1.0 and getting the same error when I `run npx docusaurus start`

this code
```
const lightCodeTheme = require('prism-react-renderer/themes/github');
const darkCodeTheme = require('prism-react-renderer/themes/dracula');
const mdxMermaid = require('mdx-mermaid');

/** @type {import('@docusaurus/types').Config} */
const config = {
...
  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          remarkPlugins: [mdxMermaid.default],
          sidebarPath: require.resolve('./sidebars.js'),
          // Please change this to your repo.
          // Remove this to remove the "edit this page" links.
          editUrl:
            'https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/',
        },
        blog: {

```

throws this error:
```
> npx docusaurus start
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
[INFO] Starting the development server...
[ERROR] ValidationError: "remarkPlugins[0]" must not be a sparse array item
```

trying instead 
```
const lightCodeTheme = require('prism-react-renderer/themes/github');
const darkCodeTheme = require('prism-react-renderer/themes/dracula');

async function createConfig() {
  const mdxMermaid = await import('mdx-mermaid')

  /** @type {import('@docusaurus/types').Config} */
  ...
    presets: [
      [
        'classic',
        /** @type {import('@docusaurus/preset-classic').Options} */
        ({
          docs: {
            remarkPlugins: [mdxMermaid.default],
            sidebarPath: require.resolve('./sidebars.js'),
            // Please change this to your repo.
            // Remove this to remove the "edit this page" links.
            editUrl:
              'https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/',
          },
          blog: {
	...	  
  };
}  
```
compiles and  shows the diagram as given in the tutorial
![image](https://user-images.githubusercontent.com/3542031/194729195-59c3da03-96be-4f3e-9e9b-e69cc1f66a30.png)


so @chungkwonryu, is there anything else you modified to make the following code work?
```
const mdxMermaid = require('mdx-mermaid');

/** @type {import('@docusaurus/types').Config} */
const config = {
```

**Comment by mathieu-souchet** [comment]
I use : 

* "@docusaurus/core": "^2.0.0"
* "@mdx-js/react": "^1.6.21"
* "mdx-mermaid": "^1.3.2"

And solution given by @chungkwonryu works for me 😃 (https://github.com/sjwall/mdx-mermaid/issues/68#issuecomment-1269513808)

Thanks !!!

**Comment by PackElend** [comment]
> And solution given by @chungkwonryu works for me 😃 ([#68 (comment)](https://github.com/sjwall/mdx-mermaid/issues/68#issuecomment-1269513808))

means you an on docusaurus/core v2.1?
Could you share your config?

**Comment by gerasimos** [comment]
Hello,

Yesterday I tried a brand new installation of Docusaurus 2.1 along with the current mdx-mermaid plugin. 

First, I get the following typescript error, If I try the proposed solution:

![image](https://user-images.githubusercontent.com/2574016/195779042-9b350109-1429-4232-83b1-22b133a30c23.png)


`Conversion of type '{ docs: { remarkPlugins: ((config?: Config | undefined) => (ast: Parent<Node<Data> | Literal<unknown, Data>, Data>) => Promise<Parent<Node<Data>, Data>>)[]; sidebarPath: string; }; blog: { ...; }; theme: { ...; }; }' to type 'Options' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Types of property 'docs' are incompatible.
    Type '{ remarkPlugins: ((config?: Config | undefined) => (ast: Parent<Node<Data> | Literal<unknown, Data>, Data>) => Promise<Parent<Node<Data>, Data>>)[]; sidebarPath: string; }' is not comparable to type 'false | Partial<Overwrite<PluginOptions, { numberPrefixParser: boolean | NumberPrefixParser; }, Diff<PluginOptions, { numberPrefixParser: boolean | NumberPrefixParser; }> & Intersection<...>>> | undefined'.
      Type '{ remarkPlugins: ((config?: Config | undefined) => (ast: Parent<Node<Data> | Literal<unknown, Data>, Data>) => Promise<Parent<Node<Data>, Data>>)[]; sidebarPath: string; }' is not comparable to type 'Partial<Overwrite<PluginOptions, { numberPrefixParser: boolean | NumberPrefixParser; }, Diff<PluginOptions, { numberPrefixParser: boolean | NumberPrefixParser; }> & Intersection<...>>>'.
        Types of property 'remarkPlugins' are incompatible.
          Type '((config?: Config | undefined) => (ast: Parent<Node<Data> | Literal<unknown, Data>, Data>) => Promise<Parent<Node<Data>, Data>>)[]' is not comparable to type 'MDXPlugin[]'.`

Can you figure out the reason?

**Comment by PackElend** [comment]
> First, I get the following typescript error, If I try the proposed solution:

how do the first lines of the config look like?
I mean these:
![image](https://user-images.githubusercontent.com/3542031/195783394-dd910ef3-0606-4207-9a4a-438728ca754e.png)

**Comment by gerasimos** [comment]
@PackElend I followed the initial recommendation https://github.com/sjwall/mdx-mermaid/issues/68#issuecomment-1269513808 

and this is how it looks 
![image](https://user-images.githubusercontent.com/2574016/195784141-e4058c9f-ea42-4150-9386-8aa85059acd3.png)

**Comment by gerasimos** [comment]
I also switched to the code proposed on the README.md file of this repo (with the `async`), but I still get the same typescript error.

**Comment by gerasimos** [comment]
Seems that a restart of nodeJS made it work, with Docusaurus 2.1 and the code in the README.md. The typescript error is still there though.

**Comment by PackElend** [comment]
I got it working in 2.1 doing 

```
async function createConfig() {
  const mdxMermaid = await import('mdx-mermaid')
```
see https://github.com/sjwall/mdx-mermaid/issues/68#issuecomment-1272403907 but that is not how it is recommended here, that concerns me a bit.

**Comment by mathieu-souchet** [comment]
> > And solution given by @chungkwonryu works for me 😃 ([#68 (comment)](https://github.com/sjwall/mdx-mermaid/issues/68#issuecomment-1269513808))
> 
> means you an on docusaurus/core v2.1? Could you share your config?

Nice to see it works for you now

I'm on Docusaurus/core 2.0.0 with a custom config because I use this [plugin](https://github.com/cloud-annotations/docusaurus-openapi) to generate my site. So my working config (`docusaurus.config.js`) is like that : 

```javascript
// @ts-check

[...]

const mdxMermaid = require('mdx-mermaid')

/** @type {import('@docusaurus/types').Config} */
const config = {
  [...]
  presets: [
    [
      "docusaurus-preset-openapi",
      /** @type {import('docusaurus-preset-openapi').Options} */
      ({
        docs: {
          sidebarPath: require.resolve("./sidebars.js"),
          editUrl: "MyRepoEditUrl",
          remarkPlugins: [mdxMermaid],
        },
      }),
    ],
  ],
  [...]
};

module.exports = config;
```

**Comment by slorber** [comment]
FYI official Docusaurus support is coming with https://github.com/facebook/docusaurus/pull/7490
