### ISSUE TITLE
Lets work together on remark-mermaidjs

### ISSUE THREAD

**Issue by remcohaszing** [sjwall/mdx-mermaid#87]
**Describe the solution you'd like**

I am the maintainer of [`remark-mermaidjs`](https://github.com/remcohaszing/remark-mermaidjs) and I recently stumbled upon this project. `remark-mermaidjs` already has several advantages over `mdx-mermaid`:

- It works with any mdast, including, but not limited to mdx.
- It isn’t tied to React.
- It supports running in a browser as well as Node.js.
- It doesn’t depend on a CDN.

I propose to work together on `remark-mermaidjs` instead of competing.

`remark-mermaidjs` doesn’t support a React component to render mermaid diagrams. That can still be developed separately.

**Describe alternatives you've considered**

1. Link `remark-mermaidjs` as an alternative in the readme.
2. You can choose to ignore this issue.

**Additional context**

N/A

**Comment by sjwall** [comment]
Hey, thanks for the details. I have added a link in the readme. Hopefully this will enable people to choose the solution that fits their use case best
