### ISSUE TITLE
Mermaid import tag shown at top of page (as plain text)

### ISSUE THREAD

**Issue by a3957273** [sjwall/mdx-mermaid#88]
**Describe the bug**
As of version 1.3.2 `mdx-mermaid` appears to show the import tag when using NextJS.  This error does not occur on mdx-mermaid version 1.2.3.

**To Reproduce**
```
// next.config.js
import nextMDX from '@next/mdx'
import remarkMermaid from 'mdx-mermaid'


const withMDX = nextMDX({
  extension: /\.mdx?$/,
  options: {
    remarkPlugins: [remarkMermaid],
    rehypePlugins: [],
  },
})

export default withMDX({
    pageExtensions: ['ts', 'tsx', 'js', 'jsx', 'md', 'mdx'],
})
```

```
// example.mdx
# Test header
```

**Expected behavior**
MDX import is not shown at top of screen.

**Screenshots**
<img width="679" alt="Screenshot 2023-02-28 at 16 54 13" src="https://user-images.githubusercontent.com/89583054/221923170-995ba3de-47a1-4eb3-8586-1c18bb41e644.png">

**Tool chain used:**
NextJS 12

**Comment by olayway** [comment]
I'm having the same issue. @a3957273 have you found any solution or workaround?
